<a href="https://colab.research.google.com/github/dwishashah/Machine-Learning/blob/main/ML_Exp8_SVM_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
%matplotlib inline
import matplotlib.pyplot as plt
df = pd.read_csv('/content/Iris(5).csv')

In [ ]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.drop('Id',axis=1,inplace=True)

In [ ]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Species']= label_encoder.fit_transform(df['Species'])

In [ ]:
x=df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]
y=df['Species']

In [ ]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(x_train.shape)
print(x_test.shape)

(120, 4)
(30, 4)


LINEAR SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear', random_state = 0)
svc.fit(x_train, y_train)
y_pred = svc.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]


In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = svc, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 97.50 %


RBF KERNEL

In [ ]:
svc1 = SVC(kernel = 'rbf', random_state = 0)
svc1.fit(x_train, y_train)
y_pred = svc1.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracies = cross_val_score(estimator = svc1, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
Accuracy: 96.67 %


POLYNOMIAL KERNEL

In [ ]:
svc2 = SVC(kernel='poly')
svc2.fit(x_train, y_train)
y_pred = svc2.predict(x_test)
 
print("Accuracy: {:.2f}%".format(svc2.score(x_test, y_test)*100))

Accuracy: 96.67%


PLOT

In [ ]:
plt.scatter(df.iloc[:,2], df.iloc[:,3])
plt.title('Petal Width vs Petal Length')
plt.xlabel('petal length')
plt.ylabel('petal width')
plt.show()